### ISSUE TITLE
Issue with code tags

### ISSUE THREAD

**Issue by Rayapudi-Hepsibah** [baynezy/Html2Markdown#112]
# Report issue:
We are facing issues in converting the Html code to Markdown using Html2Markdown library. The actual output is different from the expected output. 
**Input to Library :**            
             <code>class solution {<br>

                            int i;<br>

                             string name = “name”;<br>

                             }</code>

## Expected behavior
Expected output as per markdown syntax:
              ```

              class solution {

              int i;

              string name = “name”;

              }

              ```

## Actual Behaviour
Output from Html2Markdown Library:
             <code>class solution {

                            int i;

                             string name = “name”;

                             }</code>

## Steps to reproduce the problem

**Comment by baynezy** [comment]
@Rayapudi-Hepsibah - this should be fixed and is now published in NuGet https://www.nuget.org/packages/Html2Markdown/
