### ISSUE TITLE
Markdown generation breaks with updated HtmlAgilityPack

### ISSUE THREAD

**Issue by sake402** [baynezy/Html2Markdown#117]
# Report issue
I have a project that already has dependency on HtmlAgilityPack 1.11.38, while HtmlMarkdown depends on 1.5.0

Now with the code below
```
var converter = new Converter();
converter.Convert("<p><span>A</span>B<span>C</span></p>");
```
It works if I use HtmlAgilityPack 1.5.0 but throws exception with version 1.11.38 ``System.Exception: 'Multiple node elements can't be created.'`` from HtmlAgilityPack

The offending line is https://github.com/baynezy/Html2Markdown/blob/8dac2c7c7dc06c86b1ee5b24e8fc28e9d52e3067/src/Html2Markdown/Replacement/HtmlParser.cs#L264 with markdown ``"\r\n\r\n<span>A</span>B<span>C</span>\r\n"``

Could this be why the HtmlAgilityPack is not updated?

**Comment by baynezy** [comment]
The reason HtmlAgilityPack has not been updated is because of https://github.com/zzzprojects/html-agility-pack/issues/74#issuecomment-329476872

I cannot work with a library that cares so little for its consumers. #68 is the solution. I'm just not in a position to resolve that currently.

**Comment by baynezy** [comment]
@sake402 - I have looked at the changes required and I am going to resolve this in #119
