### ISSUE TITLE
anchor with attribute after href

### ISSUE THREAD

**Issue by chouteau** [baynezy/Html2Markdown#3]
The existing regular expression for anchor does not match other attributes after href ex:

<a href="http://www.domain.com" class="notmached">anchor</a>

you can fix it with this regexp : 

@"<a.+?href\s*=\s*['""]([^'""]+)['""][^>]*>([^<]+)</a>"

**Comment by baynezy** [comment]
Ok. I'll take a look over the weekend.

**Comment by baynezy** [comment]
Let me know if this fits your needs.

**Comment by chouteau** [comment]
Thank you, I love the way you coded it, is super good job

**Comment by baynezy** [comment]
You are very kind. Thanks for your contribution.
