### ISSUE TITLE
ConvertFile and Convert should be static

### ISSUE THREAD

**Issue by igromanru** [baynezy/Html2Markdown#44]
Please make methods Convert  and ConvertFile static. I see no point, why the Converter object has to be created.

**Comment by baynezy** [comment]
@igromanru - I deliberately avoided using static methods here. The reason is because ultimately I want to support other extensions of Markdown (e.g. GitHub Flavoured Markdown). This would require indicating when you initialise `Converter` which dialect you are working with.

**Comment by igromanru** [comment]
And you don't want to add a static method?
