### ISSUE TITLE
Can support tables?

### ISSUE THREAD

**Issue by zoujiaqing** [baynezy/Html2Markdown#46]
thaks

**Comment by baynezy** [comment]
@zoujiaqing I am unsure how I would support tables? As outlined in the [specification](https://daringfireball.net/projects/markdown/syntax#html) `table` tags should not be converted. What are you expecting to happen in this scenario?

**Comment by baynezy** [comment]
Closing due to lack of clear requirements

**Comment by zoujiaqing** [comment]
Sorry, I just saw it.
please look here : http://fletcher.github.io/MultiMarkdown-5/tables.html

**Comment by baynezy** [comment]
@zoujiaqing - don't currently have plans to implement more than the [official Markdown Spec](https://daringfireball.net/projects/markdown/syntax#html) currently. This specifies that block level elements are not converted, and markdown within them will not be converted. #35 is actually there to complete support for that.
