### ISSUE TITLE
Line breaks kill italics

### ISSUE THREAD

**Issue by ShawnTheBeachy** [baynezy/Html2Markdown#48]
I have some HTML like this:

`<i>Some text</br></i>`

It's a strange way of doing it, but I have no control over the HTML. The problem is that this causes the converter to incorrectly render the markdown. It would be nice if elements in between the `</i>` didn't break it.

**Comment by baynezy** [comment]
@RareNCool that is not valid HTML
![2017-01-10_0913](https://cloud.githubusercontent.com/assets/1049999/21800346/1f2df868-d715-11e6-9198-c7c1165fe22f.png)

What would expect to happen?

**Comment by RareNCool** [comment]
@baynezy Sorry, I was typing from memory.

Here's the exact HTML:
`<br></div><div>Whispering, <i>I love you, before long I die,
<br></i></div><div>I have travell’d a long way merely to look on you to touch you,`

from which I get (with HTML2Markdown):

![md](https://cloud.githubusercontent.com/assets/9746255/21832515/a48069ba-d779-11e6-9b5b-2d0be3bbd464.JPG)

**Comment by baynezy** [comment]
@RareNCool - what is wrong with that? Or rather what would you expect it to do? For accuracy maybe create a Gist of what you expect and then link to that here.

**Comment by baynezy** [comment]
@TastesLikeTurkey - is this still a valid issue?

**Comment by TastesLikeTurkey** [comment]
@baynezy Apologies, I forgot to ever respond. I think it still is, trying it at your demo page. For example, this:
```
<i>Hello there
I am Lord Foulspleen</i>
```
which is perfectly valid HTML, is converted to:
```
*Hello there
I am Lord Foulspleen*
```
It would be nice if line breaks in the middle of tags were handled correctly (adding a `*` at the end of the first line and the beginning of the second). But I don't know how feasible this is. If it's not something you want to bother with I can always try to come up with my own solution, too.

**Comment by baynezy** [comment]
Blocked by #45
