### ISSUE TITLE
Project should not depend on dotnetcore version of HTML Agility Pack.

### ISSUE THREAD

**Issue by idvorkin** [baynezy/Html2Markdown#66]
https://github.com/baynezy/Html2Markdown/blob/ee4fd5b0610d32ccf2ba1d8115ea770b1fb796ad/src/Html2Markdown/Html2Markdown.csproj#L14

When I tried to use the dot net standard version, I saw a unit test break on: 

     Convert_ComplexTest_002 [0:00.034] Failed: System.Exception : Multiple node elments can't be created.
     System.Exception : Multiple node elments can't be created.

Do you have more context you can share?

**Comment by baynezy** [comment]
When I upgraded this to work with .Net Core HAP had not been upgraded. I can take a look at changing back to HAP as that supports both.

**Comment by baynezy** [comment]
See zzzprojects/html-agility-pack#13

**Comment by baynezy** [comment]
Look at https://stackoverflow.com/a/42787747/1003830 when implementing
