### ISSUE TITLE
Table's wont convert

### ISSUE THREAD

**Issue by enginates** [baynezy/Html2Markdown#67]
# Report issue
Tables wont convert

## Expected behavior
Converted tables

## Actual Behavior
just send back html version

## Steps to reproduce the problem

here is the example
[table.txt](https://github.com/baynezy/Html2Markdown/files/1334866/table.txt)

this table returns back as html table

**Comment by baynezy** [comment]
@enginates - thanks for the raising the issue. This project currently only supports markdown. If you look at the [specification](https://daringfireball.net/projects/markdown/) it stipulates that [tables are not supported](https://daringfireball.net/projects/markdown/syntax#html) by intention. In fact it shouldn't even support other Markdown elements inside a certain block level elements. I have a bug to fix this #35 

Now there are extensions to the Markdown format such as [GitHub Flavoured Markdown](https://github.github.com/gfm/) which do support tables. This project does aspire to support these formats, but table conversion is actually pretty challenging.

Have a read of the [`<table>` specification](https://github.github.com/gfm/#tables-extension-) for GitHub Flavoured Markdown. Key things note are:-

- No support for `<th>` in any position other than the entire first row
- No support for block level elements in `<th>` or `<td>`
- No support for multi-line content in `<th>` or `<td>`

So if I am to support this then I need help designing what should happen when tables that cannot be converted are encountered.

I hope that makes sense?
