### ISSUE TITLE
div-Tags not handled

### ISSUE THREAD

**Issue by eFloh** [baynezy/Html2Markdown#83]
# div tags not handled by the converter.

## Expected behavior

´ div` tags should be silently removed (without producing output), except when they do not contain another block element. in that case, they should behave as `<p>` tags do

## Actual Behaviour

When the HTML source contains `<div>` tags, the Output still contains them.

## Steps to reproduce the Problem

Convert Input `<div>Some text</div>`

**Comment by baynezy** [comment]
@eFloh - thanks for contributing.

According to the [Markdown spec](https://daringfireball.net/projects/markdown/syntax#html) `div` tags are supported as is with no conversion. So the actual behaviour is correct by this rationale. In fact it should not even support Markdown elements inside HTML block level elements. I have a bug to fix this #35

**Comment by benelliott** [comment]
It would be great if this could be added as an option to the `Convert` method, even if it is technically in violation of the spec, as I think the common case for using the library is to convert HTML which was written without the Markdown spec in mind.

**Comment by JeanThirion** [comment]
> It would be great if this could be added as an option to the `Convert` method, even if it is technically in violation of the spec, as I think the common case for using the library is to convert HTML which was written without the Markdown spec in mind.

Agreed, +1 !

**Comment by baynezy** [comment]
As of version `7.0.0.49-beta`.

You can extend `Scheme` pretty easily.

```csharp
using Html2Markdown;
using Html2Markdown.Replacement;
using Html2Markdown.Scheme;

var schema = new Markdown();
var divReplacer = new DivReplacer();
schema.AddReplacer(divReplacer);

var converter = new Converter(schema);


const string html = "<div><p>Some text</p></div>";
var markdown = converter.Convert(html);
Console.WriteLine(markdown);

class DivReplacer : PatternReplacer
{
    public DivReplacer()
    {
        Pattern = "</?div[^>]*>";
        Replacement = "";
    }
}
```

This will be in the next release.
