### ISSUE TITLE
strong name assembly

### ISSUE THREAD

**Issue by Fardin11** [baynezy/Html2Markdown#84]
it would be nice to make assembly also with strong name:).

thank you for helping
regards
Fardin

**Comment by yanjun-liu** [comment]
Hi baynezy,

I see the feature request is in progress. Could I ask the release date if it's possible? Thanks a lot.

Kind regards,
Yanjun

**Comment by flensrocker** [comment]
This issue looks a bit stale but a strong name is essential if using this assembly in other projects which are strong name signed.

I added the small PR #150 with the needed changes.
The old branch for this issue is a bit outdated, so I created a new based on the current develop.

Thank you!
